### ISSUE TITLE
Table UI Requirements

### ISSUE THREAD

**Issue by BenBenBenB** [BenBenBenB/Lethal-Company-Guy-in-Chair#2]
The UI is designed to populate the clipboard with data that will be used by the AHK script to input commands to the terminal in game.

1. There will be a table for managing player names. Each row should have a checkbox, text field for the player name, and a display for the associated hotkey (for now, hotkeys are hard-coded).
2. Automatically check and enable the associated checkbox once the name field is not empty.
3. If a name field is empty, the associated checkbox should be unchecked and disabled.
4. Any time a name is edited or a box is checked, the clipboard should be updated. The clipboard will need to contain each name from the table, trimmed and separated by new line characters. If a box is unchecked, the name should be saved to the clipboard with a prefix of 'IGNOREDPLAYER:'. This will allow the AHK script to skip these when cycling through players, but allow assigned hotkeys to work regardless of checkbox status.
6. There should be a checkbox to toggle all checkboxes in the checkbox column's header. If any box is both unchecked and enabled, this master checkbox should also be unchecked. Upon checking, all checkboxes where the input name is not empty should be set to checked. Upon unchecking, all checkboxes should be unchecked.
7. There should be a button to clear all name fields.
7. There should be a button to allow the user to update their clipboard without having to edit any box or name.

**Comment by Ryan-Florida** [comment]
https://github.com/Ryan-Florida/Lethal-Company-Guy-in-Chair/pull/1 Hits all of these.

> If any box is both unchecked and enabled, this master checkbox should be unchecked.

To be clear on this, does "unchecked and enabled" mean there's a name in a given box but the checkbox has been unchecked? If that's the case, which I'm assuming it is, then need to toggle off the master checkbox in this case in the above PR.

**Comment by Ryan-Florida** [comment]
With the assumption mentioned above, [this PR](https://github.com/BenBenBenB/Lethal-Company-Guy-in-Chair/pull/1) has all the goods.

**Comment by BenBenBenB** [comment]
With PR #1 and commit 456e15c, the basic functionality desired has been added.
