### ISSUE TITLE
Save state to localStorage

### ISSUE THREAD

**Issue by BenBenBenB** [BenBenBenB/Lethal-Company-Guy-in-Chair#4]
Save inputs to the user's machine. Automatically fill in the name fields, check boxes, and hotkeys on page load.

**Comment by Ryan-Florida** [comment]
https://github.com/Ryan-Florida/Lethal-Company-Guy-in-Chair/pull/1

Got an incoming PR for this. Just gotta update tests.

**Comment by Ryan-Florida** [comment]
Tests are up-to-date and PR has been merged into the [PR against your branch](https://github.com/BenBenBenB/Lethal-Company-Guy-in-Chair/pull/1)

**Comment by BenBenBenB** [comment]
PR #1 added this.
